"use client";

import React, { useRef } from "react";
import { Exam } from "@/types";
import {
  Printer,
  ArrowLeft,
  MoreVertical,
  RefreshCcw,
} from "lucide-react";
// Dynamically import heavy browser-only libs during runtime to avoid SSR bundling issues

interface ExamViewProps {
  exam: Exam;
  onBack: () => void;
  onRegenerate?: () => void;
}

const ExamView: React.FC<ExamViewProps> = ({ exam, onBack, onRegenerate }) => {
  const examRef = useRef<HTMLDivElement | null>(null);

  const handlePrint = () => {
    window.print();
  };


  return (
    <div className="max-w-4xl mx-auto space-y-6">
      <div className="flex items-center justify-between no-print">
        <button
          type="button"
          onClick={onBack}
          className="flex items-center space-x-2 text-gray-500 hover:text-gray-700 font-medium"
        >
          <ArrowLeft size={20} />
          <span>Back to Configuration</span>
        </button>
        <div className="flex flex-wrap items-center gap-3">
          <button
            type="button"
            onClick={handlePrint}
            className="btn-primary flex items-center space-x-2"
          >
            <Printer size={18} />
            <span>Print Assignment</span>
          </button>
          {onRegenerate && (
            <button
              type="button"
              onClick={onRegenerate}
              className="flex items-center space-x-2 px-4 py-2 border border-[#E5E7EB] rounded-lg text-gray-600 hover:bg-gray-50 transition-all font-medium"
            >
              <RefreshCcw size={18} />
              <span>Regenerate</span>
            </button>
          )}
        </div>
      </div>

      <div ref={examRef} className="bg-white card overflow-hidden exam-page">
        {/* Paper Header Banner (Web view only) */}
        <div className="bg-[#1E1E1E] text-white p-6 flex items-center justify-between no-print">
          <div className="flex items-center space-x-4">
            <div className="w-10 h-10 bg-[#FB7A58] rounded flex items-center justify-center">
              <FilePlus size={24} color="white" />
            </div>
            <div>
              <h3 className="font-bold text-lg">{exam.title}</h3>
              <p className="text-gray-400 text-sm">
                Successfully generated by VedaAI •{" "}
                {new Date().toLocaleDateString()}
              </p>
            </div>
          </div>
          <button
            type="button"
            aria-label="More options"
            className="p-2 hover:bg-white/10 rounded-full transition-all"
          >
            <MoreVertical size={20} />
          </button>
        </div>

        {/* The Actual Printable Paper */}
        <div className="p-12 space-y-8">
          {/* Institutional Header */}
          <div className="text-center space-y-2 border-b-2 border-gray-900 pb-6">
            <h2 className="text-2xl font-black uppercase tracking-tight">
              {exam.institution}
            </h2>
            <div className="flex flex-col gap-4 text-sm font-bold uppercase pt-2 md:flex-row md:justify-between">
              <div className="space-y-1 text-left">
                <p>Subject: {exam.subject}</p>
                <p>Class: {exam.grade}</p>
              </div>
              <div className="space-y-1 text-right">
                <p>Time Allowed: {exam.duration}</p>
                {exam.dueDate && (
                  <p>Due Date: {new Date(exam.dueDate).toLocaleDateString()}</p>
                )}
                <p>Maximum Marks: {exam.totalMarks}</p>
              </div>
            </div>
          </div>

          {/* Student Info Fields */}
          <div className="grid grid-cols-2 gap-y-4 gap-x-12 text-sm font-bold border-b border-dashed border-gray-300 pb-8">
            <div className="flex items-end space-x-2">
              <span>Name:</span>
              <div className="flex-1 border-b border-gray-900 h-5" />
            </div>
            <div className="flex items-end space-x-2">
              <span>Roll Number:</span>
              <div className="flex-1 border-b border-gray-900 h-5" />
            </div>
            <div className="flex items-end space-x-2">
              <span>Class: {exam.grade}</span>
              <span className="ml-4">Section:</span>
              <div className="flex-1 border-b border-gray-900 h-5" />
            </div>
            <div className="flex items-end space-x-2">
              <span>Date:</span>
              <div className="flex-1 border-b border-gray-900 h-5" />
            </div>
          </div>

          {/* Sections and Questions */}
          <div className="space-y-10">
            {exam.sections.map((section, sIdx) => (
              <div key={sIdx} className="space-y-6">
                <div className="bg-gray-100 p-2 text-center border-y border-gray-900">
                  <h3 className="text-lg font-black uppercase tracking-wider">
                    {section.title}
                  </h3>
                  <p className="text-sm font-semibold italic">
                    {section.instructions}
                  </p>
                </div>

                <div className="space-y-8">
                  {section.questions.map((q, qIdx) => (
                    <div key={q.id} className="space-y-3 relative group">
                      <div className="flex items-start justify-between">
                        <div className="flex-1 space-y-4">
                          <p className="font-bold flex leading-relaxed">
                            <span className="mr-3">{qIdx + 1}.</span>
                            <span>{q.question}</span>
                          </p>

                          {q.type === "mcq" && q.options && (
                            <div className="grid grid-cols-2 gap-x-8 gap-y-3 pl-8">
                              {q.options.map((opt, i) => (
                                <div
                                  key={i}
                                  className="flex items-center space-x-2"
                                >
                                  <span className="text-sm font-bold">
                                    ({String.fromCharCode(97 + i)})
                                  </span>
                                  <span className="text-sm">{opt}</span>
                                </div>
                              ))}
                            </div>
                          )}

                          {q.type === "short" && (
                            <div className="pl-8 h-12 flex items-end">
                              <div className="w-full border-b border-gray-200" />
                            </div>
                          )}
                        </div>
                        <div className="ml-4 flex flex-col items-end shrink-0 no-print">
                          <span
                            className={`px-2 py-0.5 rounded text-[10px] uppercase font-bold text-white mb-1 ${q.difficulty === "easy"
                              ? "bg-green-500"
                              : q.difficulty === "medium"
                                ? "bg-amber-500"
                                : "bg-red-500"
                              }`}
                          >
                            {q.difficulty}
                          </span>
                          <span className="text-sm font-black text-gray-900 italic">
                            [{q.marks} Marks]
                          </span>
                        </div>
                        {/* Print-only marks */}
                        <div className="hidden print:block shrink-0 ml-4 font-black italic">
                          [{q.marks} Marks]
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
};

export default ExamView;

// Dummy icons needed for the banner
const FilePlus = ({ size, color }: { size: number; color: string }) => (
  <svg
    width={size}
    height={size}
    viewBox="0 0 24 24"
    fill="none"
    stroke={color}
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
  >
    <path d="M14.5 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7.5L14.5 2z" />
    <polyline points="14 2 14 8 20 8" />
    <line x1="12" y1="18" x2="12" y2="12" />
    <line x1="9" y1="15" x2="15" y2="15" />
  </svg>
);
